### ISSUE TITLE
 http://localhost:3001/api/getUser failed

### ISSUE THREAD

**Issue by mohamedebrahim96** [sineto/snio.portfolio#1]
Please i need your help....
how can I connect my github to the portfolio ??
```FetchError: request to http://localhost:3001/api/getUser failed, reason: connect ECONNREFUSED 127.0.0.1:3001```

**Comment by mohamedebrahim96** [comment]
<img width="1089" alt="Screen Shot 2020-07-24 at 04 53 24" src="https://user-images.githubusercontent.com/16405013/88356902-b3cc6b00-cd69-11ea-913b-31a1404c6088.png">

**Comment by sineto** [comment]
@mohamedebrahim96, you can run the decoupled API that I build for this project, here: https://github.com/sineto/snio.portfolio-api

If you have any problem, let me know.  :+1:

**Comment by mohamedebrahim96** [comment]
really thanks for your replaying.

please i need documentation how to use this project [portfolio-api](https://github.com/sineto/snio.portfolio-api) with the snio.portfolio

**Comment by sineto** [comment]
Sure, @mohamedebrahim96! It's a quit simple. Once eu have both repositories on your local directory, you can run using the command `yarn next`. If you noticed, the `snio.portfolio` repository have a `.env.local` file with a `API_HOST` env variable. You can change it if you like. The Nextjs always run the server on `:3000` port, but you can set another port with `-p` yarn flag. So:
- Change the `API_HOST` value on `.env.local` file 
- And set, to API repository (`snio.portfolio-api`), the same port to `-p` yarn flag like `yarn next -p 3001` 

The important thing about those is you have to set the same localhost port for both `API_HOST` env variable and Nextjs API server. Sorry my english, but if you cannot understand me I can try to explaine this to you again.

**Comment by sineto** [comment]
Waiting for an answer. If you need help for this issue, please reopen it. Thanks!

**Comment by mohamedebrahim96** [comment]
WOW, Works like charm!

thanks alot for ur documentation 

<img width="1724" alt="Screen Shot 2020-07-29 at 09 22 21" src="https://user-images.githubusercontent.com/16405013/88769676-04363500-d17d-11ea-94f2-1e82f4af7ca8.png">

**Comment by mohamedebrahim96** [comment]
one last thing 
how can I deploy two repo together on a server?

**in other words:**
how can make two repo works together?

**Comment by sineto** [comment]
@mohamedebrahim96, you can join the API to the front-end server just put the `utils` API directory on it. And then call the `getData` module inside `pages/index.jsx` like this:
```javascript
/* snio.portfolio repository */

// pages/index.jsx
import getData from '../utils/getData';

export const getServerSideProps = async (context) => {
	// const request = await fetch(`${process.env.API_HOST}/api/getUser`);

        // call getData module instead of fetch api
        const { repositories } = await getData('username');
	return {
		props: {
			repositories
		}
	};
};
```
After do that, you can hosting the project on Vercel that builds Nextjs servers like magic. That's the simple way. The another way is up both repositories on separated servers on Vercel. And then when you are configuring the front-end server you can setting up `Environment Variables`, giving to `API_HOST` an url to the hosted API.

Let me know if need more help! Cheers

**Comment by mohamedebrahim96** [comment]
again Cheers!🥳🥳🔥
works like charm on vercel but heroku not working
https://mohamedebrahim96.vercel.app/

thank you so much

**Comment by sineto** [comment]
Awesome, @mohamedebrahim96! Enjoy!

ps.: sorry the Heroku thing... I don't give a try to host my portfolio there, so I can't help you on it. :/
